In [1]:
import numpy as np
import pandas as pd

不确定型决策

In [2]:
A = np.array([[5*s*(e>=s) + (6*e-s)*(e<s) \
               for e in np.arange(0,50,10)] \
              for s in np.arange(0,50,10)])
print(A)

[[  0   0   0   0   0]
 [-10  50  50  50  50]
 [-20  40 100 100 100]
 [-30  30  90 150 150]
 [-40  20  80 140 200]]


悲观主义准则

In [3]:
A_min = A.min(axis=1)
print(np.argmax(A_min))
print(A_min.max())

0
0


乐观主义准则

In [4]:
A_max = A.max(axis=1)
print(np.argmax(A_max))
print(A_max.max())

4
200


等可能准则

In [5]:
A_mean = A.mean(axis=1)
print(np.argmax(A_mean))
print(A_mean.max())

4
80.0


最小机会损失准则

In [6]:
A_lost = A.max(axis=0) - A
A_lost_max = A_lost.max(axis=1)
print(np.argmin(A_lost_max))
print(A_lost_max.min())

4
40


折中主义原则

In [7]:
param = 1/3
# param = eval(input())

In [8]:
A_comp = param * A_max + (1-param) * A_min
print(np.argmax(A_comp))
print(A_comp.max())

4
39.999999999999986


=======================================
$$$$
多目标决策

In [9]:
def f(X):
    """检验层次单排序一致性
    
    输入：
        X：ndarray方阵
    
    返回：
        w：归一化特征向量
        CI
        RI
    """
    n = np.trace(X)
    C, V = np.linalg.eig(X)
    CI = np.abs((C.max() - n) / (n - 1))
    RI = {1:0, 2:0, 3:0.58, 4:0.90, 5:1.12, 6:1.24, 7:1.32, 8:1.41, 9:1.45, 10:1.49}
    RI = RI[n]
    CR = CI / RI
    if CR < 0.1:
        print('判断矩阵的一致性较好')
    else:
        print('判断矩阵的一致性较差')
    w = V[:, np.argmax(C)]
    w = np.abs(w / sum(w))
    return w, CI, RI
def f2(X):
    """检验层次总排序一致性
    
    输入：
        X：列表，元素为ndarray方阵
    
    返回：
        head：准则层权值
        body：方案层单排序权值
        tail：总排序权值
    """
    fX = [f(i) for i in X]
    head = fX[0][0]
    body = np.hstack([fX[i][0][:, np.newaxis] for i in range(1, N + 1)])
    tail = (head * body).sum(axis=1)
    CI = ([fX[i][1] for i in range(1, N + 1)] * head).sum()
    RI = ([fX[i][2] for i in range(1, N + 1)] * head).sum()
    CR = CI / RI
    if CR < 0.1:
        print('层次总排序的一致性较好')
    else:
        print('层次总排序的一致性较差')
    return head, body, tail
def f3(X):
    """构造层次分析结果表
    
    输入：
        X：列表，元素为ndarray方阵
    
    返回：
        tbl：DataFrame
    """
    head, body, tail = f2(X)
    tail = np.concatenate([[np.nan], tail])[:, np.newaxis]
    tbl = np.hstack([np.vstack([head, body]), tail])
    tbl = pd.DataFrame(tbl)
    tbl
    return tbl

In [10]:
# 课件案例
N = 6 # 方案层元素个数，A0为准则层判断矩阵，A1及往后为方案层判断矩阵
A0 = np.array([[1, 1, 1, 4, 1, 1/2],\
               [1, 1, 2, 4, 1, 1/2],\
               [1, 1/2, 1, 5, 3, 1/2],\
               [1/4, 1/4, 1/5, 1, 1/3, 1/3],\
               [1, 1, 1/3, 3, 1, 1],\
               [2, 2, 2, 3, 3, 1]])
A1 = np.array([[1, 1/4, 1/2],\
               [4, 1, 3],\
               [2, 1/3, 1]])
A2 = np.array([[1, 1/4, 1/5],\
               [4, 1, 1/2],\
               [5, 2, 1]])
A3 = np.array([[1, 3, 1/3],\
               [1/3, 1, 1/7],\
               [3, 1, 1]])
A4 = np.array([[1, 1/3, 5],\
               [3, 1, 7],\
               [1/5, 1/7, 1]])
A5 = np.array([[1, 1, 7],\
               [1, 1, 7],\
               [1/7, 1/7, 1]])
A6 = np.array([[1, 7, 9],\
               [1/7, 1, 1],\
               [1/9, 1, 1]])
A = [eval('A' + str(i)) for i in range(N + 1)]
#with pd.ExcelWriter('C:\\Users\\poposoto\\Desktop\\model\\807\\output1.xlsx') as writer:
#    f3(A).to_excel(writer)

In [11]:
# 实例1
# https://wenku.baidu.com/view/e3fabf45bb1aa8114431b90d6c85ec3a87c28b28.html
N = 3 # 方案层元素个数，A0为准则层判断矩阵，A1及往后为方案层判断矩阵
A0 = np.array([[1, 1/5, 1/3],\
              [5, 1, 3],\
              [3, 1/3, 1]])
A1 = np.array([[1, 2, 3, 4, 7],\
               [1/2, 1, 2, 3, 6],\
               [1/3, 1/2, 1, 2, 5],\
               [1/4, 1/3, 1/2, 1, 4],\
               [1/7, 1/6, 1/5, 1/4, 1]])
A2 = np.array([[0, 0, 0, 0, 0],\
               [0, 1, 1/7, 1/3, 1/5],\
               [0, 7, 1, 5, 3],\
               [0, 3, 1/5, 1, 1/3],\
               [0, 5, 1/3, 3, 1]])
A3 = np.array([[1, 1, 3, 3, 0],\
               [1, 1, 3, 3, 0],\
               [1/3, 1/3, 1, 1, 0],\
               [1/3, 1/3, 1, 1, 0],\
               [0, 0, 0, 0, 0]])
A = [eval('A' + str(i)) for i in range(N + 1)]
#with pd.ExcelWriter('C:\\Users\\poposoto\\Desktop\\model\\807\\output2.xlsx') as writer:
#    f3(A).to_excel(writer)