# 第五次上机+丘竞昆+15220172202566

导入所需包

In [1]:
import numpy as np

构造矩阵$A$和向量$b$

In [2]:
a = [[1 + (299 + I) * int(I == J) for I in range(300)] for J in range(300)]
b = [(299 + I) * I + 45150 - I for I in range(1, 301)]
a = np.array(a, dtype='float')
b = np.array(b, dtype='float')

In [3]:
display(a)

array([[300.,   1.,   1., ...,   1.,   1.,   1.],
       [  1., 301.,   1., ...,   1.,   1.,   1.],
       [  1.,   1., 302., ...,   1.,   1.,   1.],
       ...,
       [  1.,   1.,   1., ..., 597.,   1.,   1.],
       [  1.,   1.,   1., ...,   1., 598.,   1.],
       [  1.,   1.,   1., ...,   1.,   1., 599.]])

In [4]:
display(b)

array([ 45449.,  45750.,  46053.,  46358.,  46665.,  46974.,  47285.,
        47598.,  47913.,  48230.,  48549.,  48870.,  49193.,  49518.,
        49845.,  50174.,  50505.,  50838.,  51173.,  51510.,  51849.,
        52190.,  52533.,  52878.,  53225.,  53574.,  53925.,  54278.,
        54633.,  54990.,  55349.,  55710.,  56073.,  56438.,  56805.,
        57174.,  57545.,  57918.,  58293.,  58670.,  59049.,  59430.,
        59813.,  60198.,  60585.,  60974.,  61365.,  61758.,  62153.,
        62550.,  62949.,  63350.,  63753.,  64158.,  64565.,  64974.,
        65385.,  65798.,  66213.,  66630.,  67049.,  67470.,  67893.,
        68318.,  68745.,  69174.,  69605.,  70038.,  70473.,  70910.,
        71349.,  71790.,  72233.,  72678.,  73125.,  73574.,  74025.,
        74478.,  74933.,  75390.,  75849.,  76310.,  76773.,  77238.,
        77705.,  78174.,  78645.,  79118.,  79593.,  80070.,  80549.,
        81030.,  81513.,  81998.,  82485.,  82974.,  83465.,  83958.,
        84453.,  849

应用列主元消去法变换$A$和$b$

In [5]:
for K in range(300):
    # 换行
    m = a[:, K].argmax()
    temp = a[m], b[m]
    a[m], b[m] = a[K], b[K]
    a[K], b[K] = temp
    for I in range(K + 1, 300):
        # 消去
        l = a[I, K] / a[K, K]
        a[I] = a[I] - a[K] * l
        b[I] = b[I] - b[K] * l

回代计算$x$

In [6]:
x = np.zeros_like(b)
x[-1] = b[-1] / a[-1, -1]
for I in range(298, -1, -1):
    x[I] = (b[I] - a[I].dot(x)) / a[I, I]

In [7]:
display(x)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15